FROM nginx:1.24.0-alpine-slim AS development
RUN rm -rf /usr/share/nginx/html/*
COPY ./dist-dev /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
