FROM nginx:1.24.0-alpine-slim as production
RUN rm -rf /usr/share/nginx/html/*
COPY ./dist-prod /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]