export { default as HomePage } from './home/home';
export { default as ProfilePage } from './profile/profile';
export { default as ContactPage } from './contact';
export { default as ChatPage } from './chat';
export { default as ContactDetailPage } from './contact/detail';
export { default as ContactEditPage } from './contact/edit';
export { default as ContactCreatePage } from './contact/create';
export { default as Approval1Page } from "./approval1-app";
export { default as Approval1DetailPage } from "./approval1-app/detail";
export { default as Approval2Page } from "./approval2-app";
export { default as Approval2DetailPage } from "./approval2-app/detail";
export {default as LoanApp} from "./loan-app";
export {default as Step1Page} from "./loan-app/step-1";
export {default as Step2Page} from "./loan-app/step-2";
export {default as PreviewPage} from "./loan-app/preview";
export {default as DetailPage} from "./loan-app/detail";
export {default as UploadSignedPage} from "./loan-app/upload-signed";
export { ContractPage } from "./contract";
export { ContractDetailPage } from "./contract/detail";
export { DisbursePage } from "./disburse";
export { DisburseDetailPage } from "./disburse/detail";
export { RepaymentPage } from "./repayment";
export { RepaymentDetailPage } from "./repayment/detail";
export { RepaymentSchedulePage } from "./repayment_schedule";
export { RepaymentScheduleDetailPage } from "./repayment_schedule/detail";
export {TransactionPage} from "./transaction";
export { TransactionDetailPage } from "./transaction/detail";
export {ActivityUserPage} from "./activity-user";
export {MessageLogPage} from "./message-log";
export {RestructureListPage} from "./restructure";
export {RestructureDetailPage} from "./restructure/detail";
export {RestructureCreatePage} from "./restructure/create";

export {UserListPage, CreateUserPage, DetailUserPage, UpdateUserPage} from "./backoffice/user";
export {RoleListPage,} from "./backoffice/role";
